### PR TITLE
How to handle identity, type, unit and serialisation?

### PR DESCRIPTION
**Pull request by jesper-friis**
The intension with PR is to discuss and agree on the possible update of the entity schema and how to serialise serialisations of entities and data instances, as shown in the following figure: 

## Entity schema
This should not be changed unnecessary, as the DM ontology is already used by dlite and [MBueschelberger](https://github.com/MBueschelberger). Any change should be well-defined. Preferable also made backward compatible using owl:deprecated. However, I would still like to discuss the following possible changes:

1. Remove the "Identity" annotation property as it is already covered by the ontological IRI. Hence "http://onto-ns.com/meta/0.1/Person" is an IRI that stands for a given version of a datamodel for a person.

2. Change `type` from a literal to a class.
     - Pros: This would allow types to be defined ontologically and would facilitate mapping of types. 
     - Cons: Each framework using the datamodel ontology would have to ontologise their types and provide it as a separately loadable ontology. 

   In the case of DLite, this would require that the rdf serialisation module translate between the ontological type and the internal type name (bool, integer, float, fixtring, string...).

3. Change `unit` from a literal to a class.  
     - Pros: Allow units to be ontologically well-defined. Well aligned with EMMO. 
     - Cons: Unless we allow punning, this will not work well with ontologies like QUDT and OM that represents units as individusls. Like for types, each framework using the datamodel ontology must also ensure that all units are defined ontological. However, unlike types are the possible types a framework may need is open-ended, which may drastically increase the work of defining a new datamodel. The benefit of this ontologisation is also questionable,  since there already exists excellent packages  like [Pint](https://pint.readthedocs.io/en/stable/) for handling unit symbol strings and conversions. 

## Serialise
As shown in the figure is it possible to serialise entities and data instances with either subclasses or individuals. This choice does not influence the entity schema ontology, but affects interoperability. Hence, I think we should make a recommended choice and add example/documentation of how to use the ontology.

### CODE REVIEW

**Comment by quaat** [comment]
It only makes sense create individuals, also in this case. The argument for having a general ontology for describing a Person is valid, and is why we have FOAF - *however*, the individuals is a specific datamodel (entity) that will only have data-properties.

**Comment by quaat** [comment]
Regarding the changes: 
1.Remove the "Identity" annotation. The ontological IRI might be the same for different entities, but the unique id (identity) will be different. I suggest to use the same IRI for the well-defined schema, and the entities are individuals with a unique id.

**Comment by quaat** [comment]
2. Change type from a literal to a class. For a well-defined constrained system this makes sense. however, it is not always the case that the data-type given from an external system matches what exist in the ontology, and we want to focus on the data first, and the ontology second. The ontology cannot dictate which types are defined.

**Comment by quaat** [comment]
3. Change unit from a literal to a class. Again, here we cannot dictate that providers use units that are defined in existing ontologies.

**Comment by jesper-friis** [comment]
@quaat, good points. The type and unit should be data properties. Replacing this with PR #8

**Pull request closed without merging**
